FROM python:3.8.3-slim-buster

WORKDIR /app

LABEL maintainer="judhenaoma123@gmail.com"
LABEL description="Development image for Bicimaps API"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install postgresql postgresql-contrib libpq-dev gcc python-dev

RUN apt-get update \
    && apt-get install -y binutils libproj-dev gdal-bin python-gdal python3-gdal    

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
ENV GDAL_DATA=/usr/share/gdal

COPY . /app