# Generated by Django 4.1.7 on 2023-03-21 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='review_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.review'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326),
        ),
    ]
