# Generated by Django 4.1.7 on 2023-04-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0005_remove_enciclastations_review_id_review_encicla_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeparking',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='bikeparking',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='bikerepairs',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='bikerepairs',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='bikeways',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bikeways',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='bike_parking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.bikeparking'),
        ),
        migrations.AddField(
            model_name='review',
            name='bike_way_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.bikeways'),
        ),
        migrations.AlterField(
            model_name='bikeparking',
            name='parking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bikeways',
            name='way_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enciclastations',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enciclastations',
            name='station_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='encicla_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.enciclastations'),
        ),
    ]
