# Generated by Django 4.1.7 on 2023-04-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0007_bikeways_lenght'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeways',
            old_name='description',
            new_name='label',
        ),
    ]
