# Generated by Django 4.1.7 on 2023-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0010_rename_bike_way_ls_bikeways_bike_way_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enciclastations',
            name='type_of_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enciclastations',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
