# Generated by Django 4.1.7 on 2023-04-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0011_enciclastations_type_of_station_enciclastations_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enciclastations',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
