# Generated by Django 4.1.7 on 2023-04-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0012_enciclastations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enciclastations',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
