# Generated by Django 4.1.7 on 2023-04-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0013_alter_enciclastations_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
    ]
