# Generated by Django 4.1.7 on 2023-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0014_remove_user_birth_date_remove_user_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeparking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bikeparking',
            name='img_src',
        ),
        migrations.RemoveField(
            model_name='bikeparking',
            name='name',
        ),
    ]
