# Generated by Django 4.1.7 on 2023-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0015_remove_bikeparking_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeparking',
            name='parking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
