# Generated by Django 4.1.7 on 2023-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0016_alter_bikeparking_parking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
    ]
