# Generated by Django 4.1.7 on 2023-03-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0003_alter_route_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enciclastations',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enciclastations',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.review'),
        ),
    ]
