# Generated by Django 4.1.7 on 2023-03-21 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicimaps_app', '0004_alter_enciclastations_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enciclastations',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='encicla_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BikeWays',
            fields=[
                ('way_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bike_way', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('img_src', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bicimaps_app.review')),
            ],
        ),
    ]
